name: CI

on:
  pull_request:
    branches: ['master', 'main']
  push:
    branches: ['master', 'main']
  workflow_dispatch:

jobs:
  create-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install falco
        run: |
          uv tool install falco-cli --pre
          uv tool install just-bin
      - name: Generate a project
        run: falco start-project test-project -b .
        working-directory: ./
      - name: Run django checks
        run: cd test_project && just dj check --fail-level WARNING

  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install falco
        run: |
          uv tool install falco-cli --pre
          uv tool install just-bin
      - name: Generate a project
        run: falco start-project test-project -b .
        working-directory: ./
      - name: Generate requirements.txt
        run: cd test_project && just bootstrap && just lock
      - name: Build image
        run: cd test_project && docker build . -f deploy/Dockerfile


